name: Generate XML from the scheme list

on:
  push:
    branches:
      - main
    paths:
      - schemes.txt

jobs:
  generate:
    name: Generate XML and push
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Generate XML
        run: ruby generate.rb > LSApplicationQueriesSchemes.xml
      - name: Push generated XML
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Generate LSApplicationQueriesSchemes.xml"
          git push
